// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/library.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Author struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{1}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Books struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Books) Reset()         { *m = Books{} }
func (m *Books) String() string { return proto.CompactTextString(m) }
func (*Books) ProtoMessage()    {}
func (*Books) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{2}
}

func (m *Books) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Books.Unmarshal(m, b)
}
func (m *Books) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Books.Marshal(b, m, deterministic)
}
func (m *Books) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Books.Merge(m, src)
}
func (m *Books) XXX_Size() int {
	return xxx_messageInfo_Books.Size(m)
}
func (m *Books) XXX_DiscardUnknown() {
	xxx_messageInfo_Books.DiscardUnknown(m)
}

var xxx_messageInfo_Books proto.InternalMessageInfo

func (m *Books) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Authors struct {
	Authors              []*Author `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Authors) Reset()         { *m = Authors{} }
func (m *Authors) String() string { return proto.CompactTextString(m) }
func (*Authors) ProtoMessage()    {}
func (*Authors) Descriptor() ([]byte, []int) {
	return fileDescriptor_23dfc8515c58d0b2, []int{3}
}

func (m *Authors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authors.Unmarshal(m, b)
}
func (m *Authors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authors.Marshal(b, m, deterministic)
}
func (m *Authors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authors.Merge(m, src)
}
func (m *Authors) XXX_Size() int {
	return xxx_messageInfo_Authors.Size(m)
}
func (m *Authors) XXX_DiscardUnknown() {
	xxx_messageInfo_Authors.DiscardUnknown(m)
}

var xxx_messageInfo_Authors proto.InternalMessageInfo

func (m *Authors) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "api.Book")
	proto.RegisterType((*Author)(nil), "api.Author")
	proto.RegisterType((*Books)(nil), "api.Books")
	proto.RegisterType((*Authors)(nil), "api.Authors")
}

func init() { proto.RegisterFile("api/library.proto", fileDescriptor_23dfc8515c58d0b2) }

var fileDescriptor_23dfc8515c58d0b2 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0xda, 0xb4, 0x76, 0x2a, 0x82, 0x83, 0x87, 0x52, 0x0a, 0x96, 0x85, 0x62, 0x40,
	0x4c, 0xa4, 0xfe, 0x02, 0x7b, 0xe9, 0x45, 0x3c, 0xa4, 0x37, 0x4f, 0x4e, 0x96, 0xa5, 0x19, 0x92,
	0xba, 0xcb, 0xee, 0x56, 0xe8, 0xbf, 0x97, 0x64, 0x5d, 0xed, 0xed, 0xed, 0x7e, 0xf3, 0xe6, 0x0d,
	0x0f, 0x6e, 0xc9, 0x70, 0xd1, 0x72, 0x65, 0xc9, 0x9e, 0x73, 0x63, 0xb5, 0xd7, 0x38, 0x24, 0xc3,
	0x62, 0x09, 0xa3, 0xad, 0xd6, 0x0d, 0xde, 0x41, 0xea, 0xd9, 0xb7, 0x6a, 0x9e, 0xac, 0x92, 0x6c,
	0x5a, 0x86, 0x87, 0x58, 0xc2, 0xf8, 0xf5, 0xe4, 0x6b, 0x6d, 0x11, 0x61, 0xf4, 0x45, 0xc7, 0x88,
	0x7b, 0x2d, 0x32, 0x48, 0x3b, 0xaf, 0xc3, 0x7b, 0x48, 0xab, 0x4e, 0xcc, 0x93, 0xd5, 0x30, 0x9b,
	0x6d, 0xa6, 0x39, 0x19, 0xce, 0x3b, 0x54, 0x86, 0x7f, 0xf1, 0x0c, 0x93, 0xb0, 0xc7, 0xe1, 0x1a,
	0x26, 0x14, 0xe4, 0xef, 0xf4, 0xac, 0x9f, 0x0e, 0xb8, 0x8c, 0x6c, 0xf3, 0x09, 0x37, 0x6f, 0xe1,
	0xda, 0xbd, 0xb2, 0xdf, 0x2c, 0x15, 0xae, 0xe1, 0x6a, 0xa7, 0x7c, 0x08, 0xbc, 0xf4, 0x2c, 0xe0,
	0x2f, 0xce, 0x89, 0x01, 0x3e, 0x00, 0xec, 0x94, 0x8f, 0x69, 0xff, 0xa7, 0x2c, 0xae, 0x2f, 0x3c,
	0x4e, 0x0c, 0xb6, 0x4f, 0x1f, 0x8f, 0x07, 0xf6, 0xf5, 0xa9, 0xca, 0xa5, 0x3e, 0x16, 0xb2, 0xe6,
	0xb6, 0x3d, 0xbf, 0xb3, 0x6c, 0x62, 0x4b, 0x7b, 0x45, 0x56, 0xd6, 0x85, 0x69, 0x0e, 0x05, 0x19,
	0xae, 0xc6, 0x7d, 0x69, 0x2f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x59, 0x2a, 0x74, 0x49,
	0x01, 0x00, 0x00,
}
